# Generated by Django 6.0.5 on 2026-05-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, default=1234, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
